# Generated by Django 4.2.3 on 2025-01-31 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Имя')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Почта')),
                ('password', models.CharField(max_length=255, verbose_name='Пароль')),
                ('status', models.CharField(choices=[('client', 'Client'), ('petsitter', 'Pet Sitter')], default='client', max_length=20, verbose_name='Роль')),
            ],
        ),
    ]
